packages:
  - playground
  - docs
  - packages/*
  - examples/*

catalogs:
  dev:
    "@antfu/eslint-config": "^2.27.3"
    "@antfu/ni": "^24.3.0"
    "@antfu/utils": "^9.1.0"
    "@types/node": "^20.17.28"
    "bumpp": "^9.11.1"
    "eslint": "^9.23.0"
    "esno": "^4.8.0"
    "lint-staged": "^15.5.0"
    "simple-git-hooks": "^2.12.1"
    "typescript": "^5.8.2"
    "unbuild": "^2.0.0"
    "vite": "^5.4.15"
    "vitest": "^1.6.1"
